# Default values for docker-workshop-advanced.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

app:
  enabled: true
  replicas: 2
  image: lpiot/workshop-docker-advanced:app