apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: app
    spec:
      containers:
      - name: app
        image: eu.gcr.io/clustereurope2018/symfony2_demo:app-redis
        imagePullPolicy: Always
        ports:
        - containerPort: 80
