apiVersion: v1
kind: ReplicationController
metadata:
  name: hello
spec:
  replicas: 3
  selector:
    name: hello
  template:
    metadata:
      labels:
        name: hello
    spec:
      containers:
      - name: hello
        image: tutum/hello-world:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "0.1"
