apiVersion: v1
kind: Service
metadata:
  name: oxa-mysql
  labels:
    app: symfony
spec:
  ports:
    - port: 3306
  selector:
    app: symfony
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: symfony
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mo
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: oxa-mysql
  labels:
    app: symfony
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: symfony
        tier: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password.txt
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
