apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: null
  generation: 1
  labels:
    app: mysql
    version: "5.6"
  name: mysql
  selfLink: /api/v1/namespaces//replicationcontrollers/mysql
spec:
  replicas: 1
  selector:
    app: mysql
    version: "5.6"
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mysql
        version: "5.6"
      name: mysql
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          value: toto42
        image: mysql:5.6
        imagePullPolicy: IfNotPresent
        name: mysql
        resources: {}
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  replicas: 0
