apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mysql
    version: "5.6"
  name: mysql
  selfLink: /api/v1/namespaces//services/mysql
spec:
  clusterIP: <unknown>
  ports:
  - name: tcp-3306-3306-37vuu
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql
    version: "5.6"
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
