apiVersion: v1
kind: Service
metadata:
  name: symfony
  labels:
    app: symfony
spec:
  ports:
    - port: 80
  selector:
    app: symfony
    tier: frontend
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sf-pv-claim
  labels:
    app: symfony
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mo
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: symfony
  labels:
    app: symfony
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: symfony
        tier: frontend
    spec:
      containers:
      - image: oxalide/workshop-docker-advanced:app
        name: symfony
        env:
        - name: SYMFONY__DATABASE__HOST
          value: oxa-mysql
        - name: SYMFONY__DATABASE__PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password.txt
        ports:
        - containerPort: 80
          name: symfony
        volumeMounts:
        - name: symfony-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: symfony-persistent-storage
        persistentVolumeClaim:
          claimName: sf-pv-claim
